"""Add access_token to users for feed authentication

Revision ID: 1c1a5790f8a0
Revises: b248a55c4e71
Create Date: 2026-03-29 22:54:16.736275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1a5790f8a0'
down_revision = 'b248a55c4e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: owner_id, price, and currency already added to feeds in previous migrations
    
    # Generate access tokens for existing users with a Python script
    import secrets
    from sqlalchemy import text
    
    # Add column as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=64), nullable=True))
    
    # Generate tokens for existing users
    connection = op.get_bind()
    users = connection.execute(text('SELECT id FROM users')).fetchall()
    for user in users:
        token = secrets.token_urlsafe(32)
        connection.execute(
            text('UPDATE users SET access_token = :token WHERE id = :user_id'),
            {'token': token, 'user_id': user[0]}
        )
    
    # Make column non-nullable and add unique constraint
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_token', nullable=False)
        batch_op.create_unique_constraint('uq_users_access_token', ['access_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_access_token', type_='unique')
        batch_op.drop_column('access_token')

    # Note: owner_id, price, and currency are NOT removed here as they were added in previous migrations
    # ### end Alembic commands ###
