"""Add role to invitations and invited_by to users

Revision ID: b248a55c4e71
Revises: f0c82483eb8b
Create Date: 2026-03-29 22:18:16.224889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b248a55c4e71'
down_revision = 'f0c82483eb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: owner_id, price, and currency were already added to feeds in migration f0c82483eb8b
    
    # Add role to invitation_links
    with op.batch_alter_table('invitation_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))

    # Add invited_by column to users
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=True))
    
    # Add foreign key for invited_by
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_invited_by', 'users', ['invited_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_invited_by', type_='foreignkey')
        batch_op.drop_column('invited_by')

    with op.batch_alter_table('invitation_links', schema=None) as batch_op:
        batch_op.drop_column('role')

    # Note: owner_id, price, and currency are NOT removed here as they were added in migration f0c82483eb8b
    # ### end Alembic commands ###
